# Generated by Django 4.2.6 on 2023-10-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AllVilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_phone_number', models.CharField(max_length=13)),
                ('price', models.FloatField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('parking', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='villa.category')),
            ],
        ),
    ]
